/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab4n15t8;
import javax.swing.SwingWorker;
import java.util.List;
/**
 *
 * @author tranv
 */
public class bai1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai1.class.getName());

    /**
     * Creates new form bai1
     */
    public bai1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSoGiay = new javax.swing.JTextField();
        btnBatDau = new javax.swing.JButton();
        lblThoiGian = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("nhap thoi gian :");

        txtSoGiay.addActionListener(this::txtSoGiayActionPerformed);

        btnBatDau.setText("bat dau");
        btnBatDau.addActionListener(this::btnBatDauActionPerformed);

        lblThoiGian.setText(" Thời gian còn lại:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblThoiGian, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBatDau)
                    .addComponent(txtSoGiay, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoGiay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(btnBatDau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThoiGian)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatDauActionPerformed
        // TODO add your handling code here:
        try {
    int soGiay = Integer.parseInt(txtSoGiay.getText());

    if (soGiay < 0) {
        lblThoiGian.setText("Vui lòng nhập số >= 0");
        return;
    }

    lblThoiGian.setText("Thời gian còn lại: " + soGiay + " giây");
    btnBatDau.setEnabled(false);

    CountdownWorker worker = new CountdownWorker(soGiay);
    worker.execute();

} catch (NumberFormatException e) {
    lblThoiGian.setText("Vui lòng nhập số giây hợp lệ!");
}
    }//GEN-LAST:event_btnBatDauActionPerformed

    private void txtSoGiayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoGiayActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSoGiayActionPerformed
    private class CountdownWorker
            extends SwingWorker<Void, Integer> {

        private int soGiay;

        public CountdownWorker(int soGiay) {
            this.soGiay = soGiay;
        }

        @Override
        protected Void doInBackground() throws Exception {

            for (int i = soGiay; i >= 0; i--) {

                publish(i);

                Thread.sleep(1000);

                if (isCancelled()) {
                    break;
                }
            }

            return null;
        }

        @Override
        protected void process(List<Integer> chunks) {

            int thoiGian =
                    chunks.get(chunks.size() - 1);

            lblThoiGian.setText(
                "Thời gian còn lại: "
                + thoiGian + " giây"
            );
        }

        @Override
        protected void done() {

            if (!isCancelled()) {
                lblThoiGian.setText("Hết giờ!");
                btnBatDau.setEnabled(true);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatDau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JTextField txtSoGiay;
    // End of variables declaration//GEN-END:variables
}
