/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab4n15t8;
import javax.swing.SwingWorker;
import java.util.List;
/**
 *
 * @author tranv
 */
public class bai2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai2.class.getName());

    /**
     * Creates new form bai2
     */
    public bai2() {
        initComponents();
        progressBar.setMinimum(0);
    progressBar.setMaximum(100);
    progressBar.setValue(0);
    progressBar.setStringPainted(true);

    lblTrangThai.setText("Sẵn sàng");
    }
private class DownloadWorker extends SwingWorker<Void, Integer> {

    @Override
    protected Void doInBackground() throws Exception {

        for (int i = 0; i <= 100; i++) {

        
            publish(i);

        
            Thread.sleep(100);

          
            if (isCancelled()) {
                break;
            }
        }

        return null;
    }

    @Override
    protected void process(List<Integer> chunks) {

       
        int progress = chunks.get(chunks.size() - 1);

    
        progressBar.setValue(progress);

     
        lblTrangThai.setText(
            "Đang tải dữ liệu: " + progress + "%"
        );
    }

    @Override
    protected void done() {

        if (!isCancelled()) {
            progressBar.setValue(100);
            lblTrangThai.setText("Tải dữ liệu hoàn tất!");
            btnTaiDuLieu.setEnabled(true);
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTaiDuLieu = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        lblTrangThai = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTaiDuLieu.setText("“Tải dữ liệu”");
        btnTaiDuLieu.addActionListener(this::btnTaiDuLieuActionPerformed);

        lblTrangThai.setText("Sẵn sàng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(btnTaiDuLieu))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 137, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnTaiDuLieu)
                .addGap(91, 91, 91)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTrangThai)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaiDuLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaiDuLieuActionPerformed
        // TODO add your handling code here:
       
    progressBar.setValue(0);

  
    lblTrangThai.setText("Đang chuẩn bị tải...");

 
    btnTaiDuLieu.setEnabled(false);

  
    DownloadWorker worker = new DownloadWorker();

    
    worker.execute();
    }//GEN-LAST:event_btnTaiDuLieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaiDuLieu;
    private javax.swing.JLabel lblTrangThai;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
