/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab4n15t8;
import javax.swing.SwingWorker;
import java.util.List;
/**
 *
 * @author tranv
 */
public class bai3 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai3.class.getName());

    /**
     * Creates new form bai3
     */
    public bai3() {
        initComponents();
        progressBar.setMinimum(0);
    progressBar.setMaximum(100);
    progressBar.setValue(0);
    progressBar.setStringPainted(true);

    lblKetQua.setText("Chưa tính");
    }
private class PrimeSumWorker extends SwingWorker<Long, Integer> {

    private int n;
    private long tong = 0;

    public PrimeSumWorker(int n) {
        this.n = n;
    }

    // Kiểm tra số nguyên tố
    private boolean laSoNguyenTo(int so) {
        if (so < 2) {
            return false;
        }
        for (int i = 2; i <= Math.sqrt(so); i++) {

            if (so % i == 0) {
                return false;
            }
        }
        return true;
    }

    @Override
    protected Long doInBackground() throws Exception {

        for (int i = 2; i < n; i++) {

            // Kiểm tra số nguyên tố
            if (laSoNguyenTo(i)) {
                tong += i;
            }           
            int progress = (int) ((i * 100L) / (n - 1));

            publish(progress);

           
            if (isCancelled()) {
                break;
            }
        }

        return tong;
    }

    @Override
    protected void process(List<Integer> chunks) {

        int progress = chunks.get(chunks.size() - 1);

        progressBar.setValue(progress);

        lblKetQua.setText(
            "Đang tính: " + progress + "%"
        );
    }

    @Override
    protected void done() {

        try {

            long ketQua = get();

            progressBar.setValue(100);

            lblKetQua.setText(
                "Tổng các số nguyên tố < N = " + ketQua
            );

            btnTinh.setEnabled(true);

        } catch (Exception e) {

            lblKetQua.setText("Có lỗi xảy ra!");

            btnTinh.setEnabled(true);
        }
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtN = new javax.swing.JTextField();
        btnTinh = new javax.swing.JButton();
        lblKetQua = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTinh.setText("Tính");
        btnTinh.addActionListener(this::btnTinhActionPerformed);

        lblKetQua.setText("Kết quả");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblKetQua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTinh))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTinh)
                .addGap(18, 18, 18)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhActionPerformed
        // TODO add your handling code here:
        
    try {
        int n = Integer.parseInt(txtN.getText());

        if (n <= 1) {
            lblKetQua.setText("N phải lớn hơn 1");
            return;
        }

     
        progressBar.setValue(0);

      
        btnTinh.setEnabled(false);

        lblKetQua.setText("Đang tính...");

       
        PrimeSumWorker worker = new PrimeSumWorker(n);

       
        worker.execute();

    } catch (NumberFormatException e) {

        lblKetQua.setText("Vui lòng nhập số nguyên hợp lệ!");
    }
    }//GEN-LAST:event_btnTinhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTinh;
    private javax.swing.JLabel lblKetQua;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField txtN;
    // End of variables declaration//GEN-END:variables
}
