/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab4n15t8;
import java.math.BigInteger;
import java.util.HashMap;
import java.util.Map;
import javax.swing.SwingWorker;
/**
 *
 * @author tranv
 */
public class bai4 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai4.class.getName());
 // Map dùng để ghi nhớ các số Fibonacci đã tính
    private final Map<Integer, BigInteger> memo = new HashMap<>();
    /**
     * Creates new form bai4
     */
    public bai4() {
        initComponents();

        // Giá trị ban đầu
        memo.put(0, BigInteger.ZERO);
        memo.put(1, BigInteger.ONE);

        progressBar.setMinimum(0);
        progressBar.setMaximum(100);
        progressBar.setValue(0);
    }
 // Hàm Fibonacci sử dụng memoization
    private BigInteger fibonacci(int n) {
        if (memo.containsKey(n)) {
            return memo.get(n);
        }

        BigInteger result = fibonacci(n - 1).add(fibonacci(n - 2));

        // Lưu kết quả vào Map
        memo.put(n, result);

        return result;
        
    }
 private class FibonacciWorker
            extends SwingWorker<BigInteger, Integer> {

        private final int n;

        public FibonacciWorker(int n) {
            this.n = n;
        }

        @Override
        protected BigInteger doInBackground() throws Exception {

            // Tính Fibonacci
            BigInteger result = fibonacci(n);

            // Giả lập tiến trình
            for (int i = 0; i <= 100; i++) {

                Thread.sleep(5);

                setProgress(i);
            }

            return result;
        }

        @Override
        protected void done() {

            try {

                // Lấy kết quả từ SwingWorker
                BigInteger result = get();

                lblKetQua.setText(
                        "F(" + n + ") = " + result
                );

                progressBar.setValue(100);

                // Cho phép bấm lại
                btnTim.setEnabled(true);

            } catch (Exception e) {

                lblKetQua.setText(
                        "Có lỗi khi tính toán!"
                );

                btnTim.setEnabled(true);
            }
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtN = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        lblKetQua = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnTim.setText("tim");
        btnTim.addActionListener(this::btnTimActionPerformed);

        lblKetQua.setText("ket qua");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTim)
                    .addComponent(lblKetQua, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(224, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnTim)
                .addGap(18, 18, 18)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblKetQua)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
           try {

            int n = Integer.parseInt(
                    txtN.getText().trim()
            );

            // Kiểm tra N
            if (n < 0) {

                lblKetQua.setText(
                        "N phải >= 0"
                );

                return;
            }

            // Giới hạn N
            if (n > 10000) {

                lblKetQua.setText(
                        "N quá lớn, hãy nhập N <= 10000"
                );

                return;
            }

            // Thông báo đang tính
            lblKetQua.setText(
                    "Đang tính..."
            );

            progressBar.setValue(0);

            // Không cho bấm nhiều lần
            btnTim.setEnabled(false);

            // Tạo SwingWorker
            FibonacciWorker worker
                    = new FibonacciWorker(n);

            // Theo dõi tiến trình
            worker.addPropertyChangeListener(evt2 -> {

                if ("progress".equals(
                        evt2.getPropertyName())) {

                    int progress
                            = (Integer) evt2.getNewValue();

                    progressBar.setValue(progress);
                }
            });

            // Chạy background
            worker.execute();

        } catch (NumberFormatException e) {

            lblKetQua.setText(
                    "Vui lòng nhập số nguyên!"
            );
        }
    }//GEN-LAST:event_btnTimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai4().setVisible(true));
        try {

            for (
                    javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()
                    ) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(
                            info.getClassName()
                    );

                    break;
                }
            }

        } catch (
                ReflectiveOperationException
                | javax.swing.UnsupportedLookAndFeelException ex
                ) {

            logger.log(
                    java.util.logging.Level.SEVERE,
                    null,
                    ex
            );
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                () -> new bai4().setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTim;
    private javax.swing.JLabel lblKetQua;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JTextField txtN;
    // End of variables declaration//GEN-END:variables
}
