/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.lab4n15t8;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import javax.swing.JFileChooser;
import javax.swing.SwingWorker;

/**
 *
 * @author tranv
 */
public class bai5 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bai5.class.getName());
 private File selectedFile;
    /**
     * Creates new form bai5
     */
    public bai5() {
        initComponents();

        progressBar.setMinimum(0);
        progressBar.setMaximum(100);
        progressBar.setValue(0);

        lblFile.setText("Chưa chọn file");
        lblKetQua.setText("Số dòng: ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        btnChonFile = new javax.swing.JButton();
        jFileChooser2 = new javax.swing.JFileChooser();
        lblFile = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        btnDemDong = new javax.swing.JButton();
        lblKetQua = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnChonFile.setText("Chọn file");
        btnChonFile.addActionListener(this::btnChonFileActionPerformed);

        lblFile.setText("đường dẫn file");

        btnDemDong.setText("Đếm dòng");
        btnDemDong.addActionListener(this::btnDemDongActionPerformed);

        lblKetQua.setText("số dòng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnChonFile)
                            .addComponent(btnDemDong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jFileChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblFile, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                            .addComponent(lblKetQua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFileChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChonFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDemDong)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblKetQua)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChonFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();

        // Chỉ cho chọn file
        fileChooser.setFileSelectionMode(
                JFileChooser.FILES_ONLY
        );

        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {

            selectedFile = fileChooser.getSelectedFile();

            // Hiển thị đường dẫn file
            lblFile.setText(
                    selectedFile.getAbsolutePath()
            );

            lblKetQua.setText("Số dòng: ");
            progressBar.setValue(0);
        }
    }//GEN-LAST:event_btnChonFileActionPerformed

    private void btnDemDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemDongActionPerformed
        // TODO add your handling code here:
        // Kiểm tra đã chọn file chưa
        if (selectedFile == null) {

            lblKetQua.setText(
                    "Vui lòng chọn file trước!"
            );

            return;
        }

        // Reset giao diện
        progressBar.setValue(0);
        lblKetQua.setText("Đang đọc file...");

        // Không cho bấm khi đang đọc
        btnChonFile.setEnabled(false);
        btnDemDong.setEnabled(false);

        // Tạo SwingWorker
        LineCountWorker worker
                = new LineCountWorker(selectedFile);

        // Theo dõi tiến trình
        worker.addPropertyChangeListener(evt2 -> {

            if ("progress".equals(
                    evt2.getPropertyName())) {

                int progress
                        = (Integer) evt2.getNewValue();

                progressBar.setValue(progress);
            }
        });

        // Chạy background
        worker.execute();
    }//GEN-LAST:event_btnDemDongActionPerformed
 private class LineCountWorker
            extends SwingWorker<Long, Void> {

        private final File file;

        public LineCountWorker(File file) {
            this.file = file;
        }

        @Override
        protected Long doInBackground() throws Exception {

            long lineCount = 0;

            // Lấy kích thước file
            long fileSize = file.length();

            long bytesRead = 0;

            try (BufferedReader br
                    = new BufferedReader(
                            new FileReader(file))) {

                String line;

                while ((line = br.readLine()) != null) {

                    lineCount++;

                    /*
                     * Ước lượng tiến trình dựa trên
                     * vị trí file đã đọc.
                     */
                    bytesRead += line.length() + 1;

                    if (fileSize > 0) {

                        int progress = (int)
                                ((bytesRead * 100)
                                        / fileSize);

                        // Không vượt quá 100%
                        if (progress > 100) {
                            progress = 100;
                        }

                        setProgress(progress);
                    }
                }
            }

            // Hoàn thành
            setProgress(100);

            return lineCount;
        }

        @Override
        protected void done() {

            try {

                // Lấy kết quả
                long result = get();

                lblKetQua.setText(
                        "Số dòng: " + result
                );

                progressBar.setValue(100);

            } catch (Exception e) {

                lblKetQua.setText(
                        "Lỗi: " + e.getMessage()
                );

            } finally {

                // Cho phép sử dụng lại
                btnChonFile.setEnabled(true);
                btnDemDong.setEnabled(true);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new bai5().setVisible(true));
        
        try {

            for (
                    javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager
                            .getInstalledLookAndFeels()
                    ) {

                if ("Nimbus".equals(info.getName())) {

                    javax.swing.UIManager.setLookAndFeel(
                            info.getClassName()
                    );

                    break;
                }
            }

        } catch (
                ReflectiveOperationException
                | javax.swing.UnsupportedLookAndFeelException ex
                ) {

            logger.log(
                    java.util.logging.Level.SEVERE,
                    null,
                    ex
            );
        }

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                () -> new bai5().setVisible(true)
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonFile;
    private javax.swing.JButton btnDemDong;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFileChooser jFileChooser2;
    private javax.swing.JLabel lblFile;
    private javax.swing.JLabel lblKetQua;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
